// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(EventsDbContext))]
    [Migration("20231024214900_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.24");

            modelBuilder.Entity("EventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Event One",
                            EndDate = new DateTime(2023, 10, 25, 18, 48, 59, 981, DateTimeKind.Local).AddTicks(459),
                            Location = "United States",
                            StartDate = new DateTime(2023, 10, 24, 18, 48, 59, 981, DateTimeKind.Local).AddTicks(420),
                            Title = "First event"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Event Two",
                            EndDate = new DateTime(2023, 10, 26, 18, 48, 59, 981, DateTimeKind.Local).AddTicks(527),
                            Location = "United States",
                            StartDate = new DateTime(2023, 10, 24, 18, 48, 59, 981, DateTimeKind.Local).AddTicks(508),
                            Title = "Second event"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Event Three",
                            EndDate = new DateTime(2023, 10, 27, 18, 48, 59, 981, DateTimeKind.Local).AddTicks(562),
                            Location = "United States",
                            StartDate = new DateTime(2023, 10, 24, 18, 48, 59, 981, DateTimeKind.Local).AddTicks(547),
                            Title = "Third event"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Event Four",
                            EndDate = new DateTime(2023, 10, 28, 18, 48, 59, 981, DateTimeKind.Local).AddTicks(601),
                            Location = "United States",
                            StartDate = new DateTime(2023, 10, 24, 18, 48, 59, 981, DateTimeKind.Local).AddTicks(586),
                            Title = "Forth event"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
